# Generated by Django 4.0 on 2021-12-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heating_control', '0002_room_created_at_room_updated_at_valve_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='type',
            field=models.CharField(choices=[('temperature', 'temperature')], default='temperature', max_length=20),
        ),
    ]
